[package]
name = "extscan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
colored = "3.0.0"
ignore = "0.4.23"
magika = "0.2.2"
rayon = "1.11.0"
thiserror = "2.0.17"

[features]
with-magika-test = ["magika/_test"]
